
# Introduction to Matrices in Python

In this tutorial, we will cover the basics of creating, loading, and manipulating matrices using Python's `numpy` library.

## Importing necessary libraries

First, we need to import the `numpy` library, which provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. We will also import the `matplotlib` library to visualize the matrices.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Generating Matrices

You can create matrices using numpy arrays. Here are some examples:
- We can create a matrix by passing a list of lists to the `np.array` function.
- We can create a matrix of zeros using the `np.zeros` function.
- We can create a matrix of ones using the `np.ones` function.
- We can create an identity matrix using the `np.eye` function.
- We can create a matrix of random numbers using the `np.random.rand` function.

In [4]:
# Creating a matrix of zeros
matrix_zeros = np.zeros((3, 3))
print("\nMatrix of Zeros:")
print(matrix_zeros)

# Creating a matrix of ones
matrix_ones = np.ones((3, 3))
print("\nMatrix of Ones:")
print(matrix_ones)

# Creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:")
print(identity_matrix)

# Creating a matrix of random values
matrix_random = np.random.random((3, 3))
print("\nMatrix of Random Values:")
print(matrix_random)


Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Loading Matrices from Files

There are multiple ways to load matrices from files:
- We can load a matrix from a CSV file using the `np.genfromtxt` function.
- We can load a matrix from a text file using the `np.loadtxt` function.
- We can load a matrix from a NumPy binary file using the `np.load` function.

## Manipulating Matrices

We can perform various operations on matrices, such as addition, subtraction, element-wise multiplication, dot product, transposition, and inversion.

- We can add two matrices using the `+` operator.
- We can subtract one matrix from another using the `-` operator.
- We can multiply two matrices element-wise using the `*` operator.
- We can compute the dot product of two matrices using the `np.dot` function.
- We can transpose a matrix using the `.T` attribute.
- We can invert a square matrix using the `np.linalg.inv` function.

In [10]:
# Matrix addition
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_sum = matrix_a + matrix_b
print("\nMatrix A + Matrix B:")
print(matrix_sum)

# Matrix subtraction
matrix_diff = matrix_a - matrix_b
print("\nMatrix A - Matrix B:")
print(matrix_diff)

# Matrix multiplication (element-wise)
matrix_mult = matrix_a * matrix_b
print("\nElement-wise Multiplication of Matrix A and Matrix B:")
print(matrix_mult)

# Matrix multiplication (dot product)
matrix_dot = np.dot(matrix_a, matrix_b)
print("\nDot Product of Matrix A and Matrix B:")
print(matrix_dot)

# Transposing a matrix
matrix_transpose = matrix_a.T
print("\nTranspose of Matrix A:")
print(matrix_transpose)


Matrix A + Matrix B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix A - Matrix B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication of Matrix A and Matrix B:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Dot Product of Matrix A and Matrix B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
